export const subscriptions = [
  {
    personName: 'John Doe',
    subscriptionType: 'Midrange',
    date: '2024-01-15',
    price: 29.99,
    action: '',
  },
  {
    personName: 'Jane Smith',
    subscriptionType: '1 Scent',
    date: '2024-02-10',
    price: 15.99,
    action: '',
  },
  {
    personName: 'Emily Johnson',
    subscriptionType: 'Standard',
    date: '2024-03-05',
    price: 19.99,
    action: '',
  },
  {
    personName: 'Michael Brown',
    subscriptionType: 'Highend',
    date: '2024-03-20',
    price: 49.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
  {
    personName: 'Sarah Davis',
    subscriptionType: '2 Scents',
    date: '2024-04-01',
    price: 24.99,
    action: '',
  },
];
